name: table_parser
description: A lightweight library for parsing and updating table documents (CSV, ODS, XLSX). Extended version of spreadsheet_decoder with enhanced features.
version: 1.0.0
homepage: https://github.com/sestegra/table_parser

environment:
  sdk: "^3.0.0"

dependencies:
  archive: ^3.6.1
  xml: ^6.5.0
  path: ^1.9.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
